// =============================================================================
// RIXVEN — app/manifest.ts
// Dynamic PWA Web App Manifest via MetadataRoute.Manifest
//
// WHY DYNAMIC OVER STATIC site.webmanifest?
//   • Lets you reference the auto-generated /icon & /apple-icon routes
//     that Next.js creates from icon.tsx / apple-icon.tsx, so you never
//     need to ship pre-baked PNGs in /public.
//   • Type-safe — TypeScript catches invalid manifest fields at build time.
//   • Participates in the Next.js build cache; zero extra runtime cost on
//     Cloudflare Pages (rendered once, cached at the CDN edge forever).
// =============================================================================

import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    // ── Identity ─────────────────────────────────────────────────────────────
    name: "RIXVEN",
    short_name: "RIXVEN",
    description: "Engineering the computational foundations of tomorrow.",

    // ── Launch behaviour ─────────────────────────────────────────────────────
    start_url: "/",
    scope: "/",

    // ── Display ──────────────────────────────────────────────────────────────
    // "standalone" removes the browser chrome — feels like a native app.
    display: "standalone",
    // "fullscreen" would hide the status bar entirely; keep standalone for
    // iOS compatibility and predictable UX across all browsers.

    // ── Colours ──────────────────────────────────────────────────────────────
    // theme_color  → tab / status-bar chrome tint (must match viewport config
    //                in layout.tsx so there is never a colour flash on load).
    // background_color → splash screen background shown before the CSS loads.
    theme_color: "#0887C9",
    background_color: "#ffffff",

    // ── Orientation ──────────────────────────────────────────────────────────
    orientation: "portrait-primary",

    // ── Icons ────────────────────────────────────────────────────────────────
    // These paths are the *routes* generated by Next.js from your app/icon.tsx
    // and app/apple-icon.tsx files — NOT static files in /public.
    //
    // Next.js auto-registers:
    //   /icon       → 512 × 512 PNG   (from app/icon.tsx)
    //   /apple-icon → 180 × 180 PNG   (from app/apple-icon.tsx)
    //
    // The browser/OS will pick the best match for the device pixel density.
    icons: [
      {
        // Smallest addressable raster – used for home-screen thumbnails on
        // lower-DPI Android devices and the Windows tile.
        src: "/icon?size=192",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable", // Safe-zone pre-masked for adaptive icons
      },
      {
        // Full-resolution icon – PWA install prompt, splash screens, taskbars.
        src: "/icon",
        sizes: "512x512",
        type: "image/png",
        purpose: "any", // Displayed as-is (transparent bg); let the OS crop
      },
    ],

    // ── Categories (helps stores & browsers classify the PWA) ────────────────
    // https://www.w3.org/TR/manifest-app-info/#categories-member
    categories: ["productivity", "utilities", "business"],

    // ── Language & direction ─────────────────────────────────────────────────
    lang: "en-US",
    dir: "ltr",
  };
}
